{
	"name": "entwine.polydawn.io/go",
	"releases": [
		{
			"name": "v1.10",
			"items": {
				"darwin-amd64": "tar:dz2npJS2qWs6qSXYHMuUip3N3qt8nApBrRv165vboKGH7jNERj4e9W5AHPza2rPq3",
				"linux-amd64": "tar:7st3WqLqTZSvYMGL2i68xMr5F5MhjiFqoXAxigxFN7mdW8GdfaXs7CCu61jeycxdJV"
			}
			"metadata": null,
			"hazards": null
		}
		{
			"name": "v1.9",
			"items": {
				"darwin-amd64": "tar:6qEm7GETjT8q9az17uVtcAiVXz91Zy76vdNug9Gkpz15rfF3DpgrzwK5cF9CDGdnsT",
				"linux-amd64": "tar:K3bpNAsVSXXGVCzYbea8frB5x6VmbsdeoEJebFk53noqAaEh2X9cP6kFkGAUX58K8"
			},
			"metadata": null,
			"hazards": null
		},
		{
			"name": "v1.8",
			"items": {
				"darwin-amd64": "tar:9JXzbBmiymHJa9FzKbcEjgDHHtPswKYNYVSUP3en3dPi662841cZvfoMZ9t1rVGhZH",
				"linux-amd64": "tar:66TGTHk9uLGp9FsEcKiLR3Mbd69TJoacyCpoGSTWjAXr9aD9jBnBMqTBbGCbmoU92r"
			},
			"metadata": null,
			"hazards": null
		}
	]
}
