{
	"byWare": {
		"tar:3SbM6Wy1SpEKxAsEGrdTBLx8L3jHWUsLfASWAjHaT1Tc8294ok3fKnobgYKdVaHs6c": [
			"https://storage.googleapis.com/golang/go1.11.linux-amd64.tar.gz"
		],
		"tar:3iXrvwyf1ybzvz3v9jkkmH2urahgxm4c3RQZuo3g6Hu5BZbsaAoNP1gj3RDGcpgpcz": [
			"https://storage.googleapis.com/golang/go1.11.darwin-amd64.tar.gz"
		],
		"tar:66TGTHk9uLGp9FsEcKiLR3Mbd69TJoacyCpoGSTWjAXr9aD9jBnBMqTBbGCbmoU92r": [
			"https://storage.googleapis.com/golang/go1.8.linux-amd64.tar.gz"
		],
		"tar:6qEm7GETjT8q9az17uVtcAiVXz91Zy76vdNug9Gkpz15rfF3DpgrzwK5cF9CDGdnsT": [
			"https://storage.googleapis.com/golang/go1.9.darwin-amd64.tar.gz"
		],
		"tar:7st3WqLqTZSvYMGL2i68xMr5F5MhjiFqoXAxigxFN7mdW8GdfaXs7CCu61jeycxdJV": [
			"https://storage.googleapis.com/golang/go1.10.linux-amd64.tar.gz"
		],
		"tar:9JXzbBmiymHJa9FzKbcEjgDHHtPswKYNYVSUP3en3dPi662841cZvfoMZ9t1rVGhZH": [
			"https://storage.googleapis.com/golang/go1.8.darwin-amd64.tar.gz"
		],
		"tar:K3bpNAsVSXXGVCzYbea8frB5x6VmbsdeoEJebFk53noqAaEh2X9cP6kFkGAUX58K8": [
			"https://storage.googleapis.com/golang/go1.9.linux-amd64.tar.gz"
		],
		"tar:dz2npJS2qWs6qSXYHMuUip3N3qt8nApBrRv165vboKGH7jNERj4e9W5AHPza2rPq3": [
			"https://storage.googleapis.com/golang/go1.10.darwin-amd64.tar.gz"
		]
	}
}
